import type { ContractAddresses } from './types';

// Load contract addresses from deployment
let addresses: ContractAddresses | null = null;

export async function loadAddresses(): Promise<ContractAddresses> {
  if (addresses) return addresses;

  try {
    // Try to load from addresses.json (generated by deployment script)
    const response = await fetch('/src/contracts/addresses.json');
    if (!response.ok) {
      throw new Error('Addresses file not found');
    }
    addresses = await response.json();
    return addresses!;
  } catch (error) {
    console.warn('Failed to load contract addresses, using defaults:', error);

    // Fallback to default Anvil addresses (will be replaced after deployment)
    addresses = {
      factory: '0x0000000000000000000000000000000000000000',
      pool: '0x0000000000000000000000000000000000000000',
      usdc: '0x0000000000000000000000000000000000000000',
      wbtc: '0x0000000000000000000000000000000000000000',
      eth: '0x0000000000000000000000000000000000000000',
      deployer: '0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266', // Anvil default
    };
    return addresses;
  }
}

export function getAddresses(): ContractAddresses | null {
  return addresses;
}

export function clearAddresses(): void {
  addresses = null;
}
