#!/usr/bin/env bun
/**
 * @title Generate Zero Values
 * @notice Generates zero values for Poseidon Merkle tree
 * @dev Computes zeros[i] = Poseidon(zeros[i-1], zeros[i-1])
 */

import { buildPoseidon } from "circomlibjs";
import { writeFileSync } from "fs";
import { resolve, dirname } from "path";
import { fileURLToPath } from "url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

const TREE_HEIGHT = 32;

async function generateZeroValues() {
  console.log(`🌲 Generating zero values for Merkle tree (height: ${TREE_HEIGHT})...\n`);

  try {
    // Build Poseidon instance
    const poseidon = await buildPoseidon();

    // Compute zero values recursively
    const zeros: bigint[] = [];
    zeros[0] = BigInt(0); // Base case: zero leaf

    console.log(`Level 0: ${zeros[0].toString()}`);

    for (let i = 1; i <= TREE_HEIGHT; i++) {
      // zeros[i] = Poseidon(zeros[i-1], zeros[i-1])
      const hash = poseidon([zeros[i - 1], zeros[i - 1]]);
      zeros[i] = poseidon.F.toObject(hash);
      console.log(`Level ${i}: ${zeros[i].toString()}`);
    }

    // Generate Solidity constant array
    const solidityCode = generateSolidityZeros(zeros);
    const solidityPath = resolve(__dirname, "../../contracts/src/darkpool/libraries/generated/Zeros.sol");

    writeFileSync(solidityPath, solidityCode, "utf8");
    console.log(`\n✅ Zeros.sol written to ${solidityPath}`);

    // Generate TypeScript/JavaScript constants
    const tsCode = generateTypeScriptZeros(zeros);
    const tsPath = resolve(__dirname, "../generated/zeros.ts");

    writeFileSync(tsPath, tsCode, "utf8");
    console.log(`✅ zeros.ts written to ${tsPath}`);

    // Generate JSON for easy import
    const jsonData = {
      treeHeight: TREE_HEIGHT,
      zeros: zeros.map((z) => "0x" + z.toString(16).padStart(64, "0")),
    };

    const jsonPath = resolve(__dirname, "../generated/zeros.json");
    writeFileSync(jsonPath, JSON.stringify(jsonData, null, 2), "utf8");
    console.log(`✅ zeros.json written to ${jsonPath}`);

    console.log("\n🎉 Zero values generated successfully!");
    console.log("\n📋 Next steps:");
    console.log("1. Update LibMerkleTree.sol to import and use Zeros library");
    console.log("2. Use zeros.ts in your TypeScript proof builder");
  } catch (error) {
    console.error("❌ Error generating zero values:", error);
    process.exit(1);
  }
}

function generateSolidityZeros(zeros: bigint[]): string {
  const zeroValues = zeros
    .map((z, i) => `        zeros[${i}] = bytes32(uint256(${z}));`)
    .join("\n");

  return `// SPDX-License-Identifier: MIT
// Generated by generate-zeros.ts
pragma solidity ^0.8.28;

/**
 * @title Zeros
 * @notice Pre-computed zero values for Poseidon Merkle tree
 * @dev zeros[i] = Poseidon(zeros[i-1], zeros[i-1])
 */
library Zeros {
    /**
     * @notice Get zero value for a given tree level
     * @param level Tree level (0 = leaf, ${TREE_HEIGHT} = root)
     * @return Zero value as bytes32
     */
    function getZero(uint8 level) internal pure returns (bytes32) {
        require(level <= ${TREE_HEIGHT}, "Level too high");

        bytes32[${TREE_HEIGHT + 1}] memory zeros;

${zeroValues}

        return zeros[level];
    }

    /**
     * @notice Get all zero values
     * @return Array of zero values for all levels
     */
    function getAllZeros() internal pure returns (bytes32[${TREE_HEIGHT + 1}] memory zeros) {
${zeroValues}
        return zeros;
    }
}
`;
}

function generateTypeScriptZeros(zeros: bigint[]): string {
  const zeroArray = zeros.map((z) => `  "${z.toString()}",`).join("\n");

  return `/**
 * @title Zero Values
 * @notice Pre-computed zero values for Poseidon Merkle tree
 * @dev Generated by generate-zeros.ts
 */

export const TREE_HEIGHT = ${TREE_HEIGHT};

export const ZEROS: string[] = [
${zeroArray}
];

export const ZEROS_HEX: string[] = ZEROS.map(z => "0x" + BigInt(z).toString(16).padStart(64, "0"));

export function getZero(level: number): string {
  if (level > ${TREE_HEIGHT}) {
    throw new Error(\`Level \${level} exceeds tree height ${TREE_HEIGHT}\`);
  }
  return ZEROS[level];
}

export function getZeroHex(level: number): string {
  if (level > ${TREE_HEIGHT}) {
    throw new Error(\`Level \${level} exceeds tree height ${TREE_HEIGHT}\`);
  }
  return ZEROS_HEX[level];
}
`;
}

// Run
await generateZeroValues();
