// SPDX-License-Identifier: MIT
pragma solidity =0.8.35;

// PROTO — clamped QUARTIC B-spline, NON-UNIFORM knots (the shipped fits are uniform-in-OFFSET ⇒
// non-uniform in x), packed 2-slot segments + prefix integrals (O(1) area) + binary-search lookup.
// This is the production-port candidate shape for Spline.sol. Two jobs:
//   1. PARITY: evaluate the exact fitted objects from research/stable-core (quartic_vectors.json,
//      generated by export_parity_vectors.ts) and assert Sol ≡ TS within integer truncation.
//   2. GAS: eval/area/push numbers for the non-uniform variant (binary search vs uniform x/h index).
// Production port itself is gated on owner go + security review.
import {Test} from "forge-std/Test.sol";
import {console2} from "forge-std/console2.sol";

library NUQuartic {
  int256 internal constant P = 1e18;
  int256 internal constant Q = 1e9; // pbps fixed-point: y stored/returned as pbps*Q

  // slotA = c0..c3 (4x int64); slotB = c4 (int64) + S prefix integral (int128) + x0,h (2x uint32).
  struct Seg {
    int64 c0;
    int64 c1;
    int64 c2;
    int64 c3;
    int64 c4;
    int128 S; // ∫y dx from x=0 to left edge (pbps*Q * x-units)
    uint32 x0;
    uint32 h;
  }

  struct Curve {
    uint32 m; // segment count
    Seg[] segs;
  }

  error NotMonotone();
  error BadInput();
  error CoeffOverflow();

  /// @notice Validate Δw≥0 (O(n) int compares ⇒ monotone at ANY degree), convert clamped quartic
  ///         B-spline on ARBITRARY strictly-increasing interior knots to power basis, store packed.
  /// @param wQ control weights, length nInt+5, pbps*Q. Nondecreasing ⇔ monotone curve.
  function pushConvert(
    Curve storage c,
    uint256 xspan,
    uint256[] memory interior,
    int256[] memory wQ
  ) internal {
    uint256[] memory t = _validate(xspan, interior, wQ);
    c.m = uint32(wQ.length - 4); // span count (clamped quartic)
    int256 S = 0;
    for (uint256 j = 0; j + 4 < wQ.length; ++j) {
      S = _buildSeg(c, t, wQ, j, S);
    }
  }

  /// @dev Δw≥0 + strictly-increasing interior knots ⇒ clamped degree-4 knot vector:
  ///      5x 0, interior, 5x xspan.
  function _validate(uint256 xspan, uint256[] memory interior, int256[] memory wQ)
    private
    pure
    returns (uint256[] memory t)
  {
    uint256 n = wQ.length;
    if (n < 5 || interior.length != n - 5) revert BadInput();
    for (uint256 i = 1; i < n; ++i) {
      if (wQ[i] < wQ[i - 1]) revert NotMonotone();
    }
    t = new uint256[](n + 5);
    uint256 prev = 0;
    for (uint256 j = 0; j < interior.length; ++j) {
      uint256 kx = interior[j];
      if (kx <= prev || kx >= xspan) revert BadInput();
      t[5 + j] = kx;
      prev = kx;
    }
    for (uint256 i = n; i < n + 5; ++i) {
      t[i] = xspan;
    }
  }

  /// @dev convert span j to power basis, store it, return S + exact segment integral.
  function _buildSeg(Curve storage c, uint256[] memory t, int256[] memory wQ, uint256 j, int256 S)
    private
    returns (int256)
  {
    int256[5] memory k = _segCoeffs(t, wQ, j + 4);
    _store(c, j, k, S, t[j + 4], t[j + 5] - t[j + 4]);
    // exact full-segment integral: h*(60c0+30c1+20c2+15c3+12c4)/60
    return S
      + (int256(t[j + 5] - t[j + 4]) * (60 * k[0] + 30 * k[1] + 20 * k[2] + 15 * k[3] + 12 * k[4]))
      / 60;
  }

  /// @dev power basis on local u∈[0,1]: c0..c2 from the left jet, c3/c4 from the right-end (y,d).
  ///      All five straight from de Boor per span — value/slope/y'' are continuous, so evaluating
  ///      the left jet inside this span equals the previous span's right jet (no carry needed).
  function _segCoeffs(uint256[] memory t, int256[] memory wQ, uint256 s)
    private
    pure
    returns (int256[5] memory k)
  {
    int256 ih = int256(t[s + 1] - t[s]);
    int256 c0 = _deBoor4(t, wQ, s, t[s]);
    int256 c1 = (_deBoorD1(t, wQ, s, t[s]) * ih) / D;
    int256 c2 = (_deBoorD2(t, wQ, s, t[s]) * ih * ih) / (2 * D);
    int256 A = _deBoor4(t, wQ, s, t[s + 1]) - c0 - c1 - c2;
    int256 B = (_deBoorD1(t, wQ, s, t[s + 1]) * ih) / D - c1 - 2 * c2;
    k = [c0, c1, c2, 4 * A - B, B - 3 * A];
  }

  function _store(Curve storage c, uint256 j, int256[5] memory k, int256 S, uint256 x0, uint256 h)
    private
  {
    int256 lim = int256(uint256(type(uint64).max) / 2);
    for (uint256 i = 0; i < 5; ++i) {
      if (k[i] > lim || k[i] < -lim) revert CoeffOverflow();
    }
    Seg memory sg = Seg({
      c0: int64(k[0]),
      c1: int64(k[1]),
      c2: int64(k[2]),
      c3: int64(k[3]),
      c4: int64(k[4]),
      S: int128(S),
      x0: uint32(x0),
      h: uint32(h)
    });
    if (j < c.segs.length) c.segs[j] = sg;
    else c.segs.push(sg);
  }

  /// @dev de Boor degree 4 at x in span s. wQ already pbps*Q.
  function _deBoor4(uint256[] memory t, int256[] memory wQ, uint256 s, uint256 x)
    private
    pure
    returns (int256)
  {
    int256[5] memory d;
    for (uint256 k = 0; k < 5; ++k) {
      d[k] = wQ[s - 4 + k];
    }
    for (uint256 r = 1; r <= 4; ++r) {
      for (uint256 j = 4; j >= r; --j) {
        int256 den = int256(t[j + 1 + s - r] - t[j + s - 4]);
        int256 num = int256(x - t[j + s - 4]);
        d[j] = (d[j - 1] * (den - num) + d[j] * num) / den;
      }
    }
    return d[4];
  }

  // Extra fixed-point scale for the derivative pyramids: slope/curvature truncation feeds c2=s0*h^2/2,
  // so a 1-unit s0 error costs h^2/2 units of y (1.25e7 at a 5000-unit span). D=1e6 caps that at ~13.
  int256 internal constant D = 1e6;

  /// @dev q_i = 4*(w[i+1]-w[i])*D/(t[i+5]-t[i+1]) — first-derivative ctrl (degree 3), pbps*Q*D per x.
  function _q(uint256[] memory t, int256[] memory wQ, uint256 i) private pure returns (int256) {
    return (4 * (wQ[i + 1] - wQ[i]) * D) / int256(t[i + 5] - t[i + 1]);
  }

  /// @dev first derivative: degree-3 de Boor over q.
  function _deBoorD1(uint256[] memory t, int256[] memory wQ, uint256 s, uint256 x)
    private
    pure
    returns (int256)
  {
    int256[4] memory d;
    for (uint256 k = 0; k < 4; ++k) {
      d[k] = _q(t, wQ, s - 4 + k);
    }
    for (uint256 r = 1; r <= 3; ++r) {
      for (uint256 j = 3; j >= r; --j) {
        int256 den = int256(t[j + s - r + 1] - t[j + s - 3]);
        int256 num = int256(x - t[j + s - 3]);
        d[j] = (d[j - 1] * (den - num) + d[j] * num) / den;
      }
    }
    return d[3];
  }

  /// @dev second derivative: r_i = 3*(q[i+1]-q[i])/(t[i+5]-t[i+2]), degree-2 de Boor.
  function _deBoorD2(uint256[] memory t, int256[] memory wQ, uint256 s, uint256 x)
    private
    pure
    returns (int256)
  {
    int256[3] memory d;
    for (uint256 k = 0; k < 3; ++k) {
      uint256 i = s - 4 + k;
      d[k] = (3 * (_q(t, wQ, i + 1) - _q(t, wQ, i))) / int256(t[i + 5] - t[i + 2]);
    }
    for (uint256 r = 1; r <= 2; ++r) {
      for (uint256 j = 2; j >= r; --j) {
        int256 den = int256(t[j + s - r + 1] - t[j + s - 2]);
        int256 num = int256(x - t[j + s - 2]);
        d[j] = (d[j - 1] * (den - num) + d[j] * num) / den;
      }
    }
    return d[2];
  }

  /// @dev binary search: largest i with segs[i].x0 <= x.
  function _seg(Curve storage c, uint256 x) private view returns (Seg storage) {
    uint256 lo = 0;
    uint256 hi = c.m - 1;
    while (lo < hi) {
      uint256 mid = (lo + hi + 1) >> 1;
      if (uint256(c.segs[mid].x0) <= x) lo = mid;
      else hi = mid - 1;
    }
    return c.segs[lo];
  }

  /// @notice eval → pbps*Q (full precision for parity; production would /Q or rescale).
  function evalQ(Curve storage c, uint256 x) internal view returns (int256) {
    Seg storage sg = _seg(c, x);
    unchecked {
      uint256 dx = x > uint256(sg.x0) ? x - uint256(sg.x0) : 0;
      if (dx > uint256(sg.h)) dx = uint256(sg.h);
      int256 u = int256((dx * uint256(P)) / uint256(sg.h));
      int256 v = (int256(sg.c4) * u) / P;
      v = ((int256(sg.c3) + v) * u) / P;
      v = ((int256(sg.c2) + v) * u) / P;
      v = ((int256(sg.c1) + v) * u) / P;
      return int256(sg.c0) + v;
    }
  }

  /// @notice O(1) integral over [x1,x2] via prefix S — touches ONLY the 2 boundary segments.
  ///         Returns pbps*Q * x-units.
  function areaQ(Curve storage c, uint256 x1, uint256 x2) internal view returns (int256) {
    if (x1 >= x2) return 0;
    return _at(c, x2) - _at(c, x1);
  }

  /// @dev cumulative integral from 0 to x: S_i + local quintic primitive.
  function _at(Curve storage c, uint256 x) private view returns (int256) {
    Seg storage sg = _seg(c, x);
    unchecked {
      uint256 dx = x > uint256(sg.x0) ? x - uint256(sg.x0) : 0;
      if (dx > uint256(sg.h)) dx = uint256(sg.h);
      int256 u = int256((dx * uint256(P)) / uint256(sg.h));
      int256 u2 = (u * u) / P;
      int256 u3 = (u2 * u) / P;
      int256 u4 = (u3 * u) / P;
      int256 u5 = (u4 * u) / P;
      int256 sum = int256(sg.c0) * u + (int256(sg.c1) * u2) / 2 + (int256(sg.c2) * u3) / 3
        + (int256(sg.c3) * u4) / 4 + (int256(sg.c4) * u5) / 5;
      return int256(sg.S) + (int256(uint256(sg.h)) * sum) / P;
    }
  }
}

contract QuarticProtoTest is Test {
  using NUQuartic for NUQuartic.Curve;

  struct AreaVec {
    int256 aQ;
    uint256 x1;
    uint256 x2;
  }

  uint256 internal constant XSPAN = 10000;

  NUQuartic.Curve[] internal curves; // one per shape in quartic_vectors.json
  string[] internal names;
  NUQuartic.Curve internal cFresh;

  string internal vec;

  // DCE guards
  int256 internal sOut;
  uint256 internal sGas;

  function setUp() public {
    vec = vm.readFile("test/proto/quartic_vectors.json");
    names = vm.parseJsonKeys(vec, "$"); // every shape family — generic, no hardcoded list
    for (uint256 i = 0; i < names.length; ++i) {
      curves.push();
      this.loadCurve(i); // external call: keeps the de Boor pyramids out of setUp's stack frame
    }
  }

  /// @dev external so pushConvert isn't inlined into the setUp loop (via_ir stack-depth limit).
  function loadCurve(uint256 i) external {
    string memory key = string.concat(".", names[i]);
    uint256[] memory interior = vm.parseJsonUintArray(vec, string.concat(key, ".interior"));
    int256[] memory wQ = vm.parseJsonIntArray(vec, string.concat(key, ".wQ"));
    curves[i].pushConvert(XSPAN, interior, wQ);
  }

  // -- parity: Sol ≡ TS on the exact fitted objects, EVERY shape family ---------------------
  function test_parity_all() public view {
    for (uint256 c = 0; c < names.length; ++c) {
      _parityEval(c);
      _parityArea(c);
    }
  }

  function _parityEval(uint256 c) internal view {
    string memory key = string.concat(".", names[c]);
    uint256[] memory xs = vm.parseJsonUintArray(vec, string.concat(key, ".xs"));
    int256[] memory yQ = vm.parseJsonIntArray(vec, string.concat(key, ".yQ"));
    int256 worst = 0;
    for (uint256 i = 0; i < xs.length; ++i) {
      int256 d = curves[c].evalQ(xs[i]) - yQ[i];
      if (d < 0) d = -d;
      if (d > worst) worst = d;
    }
    console2.log(string.concat("parity eval ", names[c], " worst |dy| (pbps*1e9):"), worst);
    // worst ≈ few units = ~1e-9 pbps (D-scaled derivative pyramids kill the c2·h² truncation);
    // 8+ orders below the 0.5 pbps fit tolerance.
    assertLe(worst, 200, string.concat("eval parity ", names[c]));
  }

  function _parityArea(uint256 c) internal view {
    bytes memory raw = vm.parseJson(vec, string.concat(".", names[c], ".areas"));
    AreaVec[] memory av = abi.decode(raw, (AreaVec[]));
    for (uint256 i = 0; i < av.length; ++i) {
      int256 d = curves[c].areaQ(av[i].x1, av[i].x2) - av[i].aQ;
      if (d < 0) d = -d;
      int256 mag = av[i].aQ < 0 ? -av[i].aQ : av[i].aQ;
      // 1e-6 rel + 0.1 pbps·x-unit abs floor (symmetric shapes integrate to ~0 over full domain).
      assertLe(d, mag / 1_000_000 + 100_000_000, string.concat("area parity ", names[c]));
    }
  }

  // -- structural gate: Δw≥0 ⇒ monotone, EVERY shape ---------------------------------------
  function test_monotone_all() public view {
    for (uint256 c = 0; c < names.length; ++c) {
      int256 prev = curves[c].evalQ(0);
      for (uint256 x = 10; x <= XSPAN; x += 10) {
        int256 y = curves[c].evalQ(x);
        assertGe(y, prev - 10, string.concat("nondecreasing ", names[c])); // 1e-8 pbps slack
        prev = y;
      }
    }
  }

  function test_rejects_nonMonotone() public {
    string memory key = string.concat(".", names[0]);
    uint256[] memory interior = vm.parseJsonUintArray(vec, string.concat(key, ".interior"));
    int256[] memory wQ = vm.parseJsonIntArray(vec, string.concat(key, ".wQ"));
    wQ[wQ.length - 1] = wQ[0] - 1; // force a decrease at the end
    vm.expectRevert(NUQuartic.NotMonotone.selector);
    this.pushExt(interior, wQ);
  }

  function pushExt(uint256[] memory interior, int256[] memory wQ) external {
    cFresh.pushConvert(XSPAN, interior, wQ);
  }

  // -- gas PER PROFILE (worst-case swap primitives): eval + O(1) full-range area -------------
  function test_gas_per_profile() public {
    for (uint256 c = 0; c < names.length; ++c) {
      uint256 g0 = gasleft();
      int256 r = curves[c].evalQ(4990);
      uint256 gEval = g0 - gasleft();
      g0 = gasleft();
      int256 r2 = curves[c].areaQ(200, 9800); // ~full-range integral (worst span)
      uint256 gArea = g0 - gasleft();
      sOut = r + r2;
      sGas = gEval + gArea;
      console2.log(string.concat("gas ", names[c], " segs:"), curves[c].m);
      console2.log("   eval / area:", gEval, gArea);
      assertGt(sGas, 500);
    }
  }
}
