// SPDX-License-Identifier: MIT
pragma solidity =0.8.35;

import {Vm} from "forge-std/Vm.sol";
import {stdJson} from "forge-std/StdJson.sol";

/// @notice Live-mark pool seed amounts from `deploy/chapel-seed-amounts.json`
///         (generated by `keepers/bots/scripts/gen-chapel-seed-amounts.ts`).
library ChapelSeedAmounts {
    using stdJson for string;

    Vm private constant VM = Vm(address(uint160(uint256(keccak256("hevm cheat code")))));

    address constant USDC = 0x6dF80a290E0585dad752c25f2808E83b5624290d;
    address constant USDT = 0xB7b7722369Ab72cb044DE6bb511A4586F3a7dD64;
    address constant USD1 = 0xC28bE4D407096E771F932c202F13D866B4d6BA07;
    address constant USDE = 0xebF751546832ec77a039083E9FDd8158B21c0172;
    address constant FDUSD = 0x4Aa480f3dc3a1f08c24472E083fBDBE919b8BdFc;
    address constant BTCB = 0xd719319e853670ac938e426fbdB70CFdb34c11Fa;
    address constant ETH = 0x24Ff1aCD4e8fdBFEBee2e7e63ad36B1E72821189;
    address constant WBNB = 0x31B7DCA9e901F7D34fb4a3Ee07eD2994de16685D;
    address constant CAKE = 0xa7E62dd82789346bEb48a80227B5d926c6403400;
    address constant XAUT = 0xd384aC4696FA230c9049F6534Fc35aC3af586073;

    string constant PATH = "deploy/chapel-seed-amounts.json";

    function seedAmount(address tok, uint256 seedUsdcFallback) internal view returns (uint256) {
        // Always prefer live JSON; fallback only for stables if gen not run.
        string memory sym = _sym(tok);
        if (VM.exists(PATH)) {
            string memory json = VM.readFile(PATH);
            return json.readUint(string.concat(".amountsWei.", sym));
        }
        if (tok == USDC || tok == USDT || tok == USD1 || tok == USDE || tok == FDUSD) {
            return seedUsdcFallback;
        }
        revert("ChapelSeedAmounts: run keepers/bots/scripts/gen-chapel-seed-amounts.ts");
    }

    function _sym(address tok) private pure returns (string memory) {
        if (tok == USDC) return "USDC";
        if (tok == USDT) return "USDT";
        if (tok == USD1) return "USD1";
        if (tok == USDE) return "USDE";
        if (tok == FDUSD) return "FDUSD";
        if (tok == BTCB) return "BTCB";
        if (tok == ETH) return "ETH";
        if (tok == WBNB) return "WBNB";
        if (tok == CAKE) return "CAKE";
        if (tok == XAUT) return "XAUT";
        revert("ChapelSeedAmounts: unknown token");
    }
}
